; This file was auto-generated by drush_make
core = 6.x

api = 2
projects[drupal][version] = "6.24"

; Modules
projects[admin_menu][version] = "1.8"

projects[cck][version] = "2.9"

projects[devel][version] = "1.26"

projects[emfield][version] = "2.5"

projects[features][version] = "1.2"

projects[link][version] = "2.9"

projects[media_vimeo][version] = "1.1"

projects[media_youtube][version] = "1.3"

projects[pathauto][version] = "1.6"

projects[token][version] = "1.18"

projects[views][version] = "2.16"

; Themes
projects[framework][version] = "3.3"

