<?php

/**
 * @file tldwapi.module
 * TLDW API
 */

/**
 * Implementation of hook_menu
 */
function tldwapi_menu() {
  $items['tldwapi/search'] = array(
    'title' => 'TLDW API',
    'page callback' => 'tldwapi_pages_search',
    'access arguments' => array('access content'),
    'file' => 'tldwapi.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $items['tldwapi/search/%'] = array(
    'title' => 'TLDW API by format',
    'page callback' => 'tldwapi_pages_search',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'file' => 'tldwapi.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}
